SweltornInteriors_MapScripts::
	.byte 0

SweltornInteriors_EventScript_Sweltornmin1::
	msgbox SweltornInteriors_Text_Sweltornmin1, MSGBOX_NPC
	end

SweltornInteriors_EventScript_Sweltornmin2::
	msgbox SweltornInteriors_Text_Sweltornmin2, MSGBOX_NPC
	end

SweltornInteriors_EventScript_Sweltornmin3::
	msgbox SweltornInteriors_Text_Sweltornmin3, MSGBOX_NPC
	end

SweltornInteriors_EventScript_Sweltornmin4::
	msgbox SweltornInteriors_Text_Sweltornmin4, MSGBOX_NPC
	end

SweltornInteriors_EventScript_Sweltornmin5::
	msgbox SweltornInteriors_Text_Sweltornmin5, MSGBOX_NPC
	end

SweltornInteriors_EventScript_Sweltornmin6::
	msgbox SweltornInteriors_Text_Sweltornmin6, MSGBOX_NPC
	end

SweltornInteriors_Text_Sweltornmin1:
	.string "I'm supposed to be the door guard\n"
	.string "for this checkpoint. But like,\l"
	.string "what am I even guarding for?\l"
	.string "No Pokémon come past the cave,\l"
	.string "and there aren't really\l"
	.string "criminals looking to ravage\l"
	.string "the desert, or whatever.\p"
	.string "Hey, I don't mind. Pay me for\n"
	.string "nothing, that's my kinda job.$"

SweltornInteriors_Text_Sweltornmin2:
	.string "The permanent sandstorm swirling\n"
	.string "around Sweltorn may be the perfect\l"
	.string "excuse to break out your\l"
	.string "Rock type team members.\l"
	.string "They'll be even bulkier in\l"
	.string "this weather.$"

SweltornInteriors_Text_Sweltornmin3:
	.string "Being in the desert made me\n"
	.string "really want to play a game that\l"
	.string "was set in one, so I dusted off\l"
	.string "my copy of The Sims 2 for the\l"
	.string "Gameboy Advance and dove in.\p"
	.string "Contrary to most Sims games, this\n"
	.string "one is actually an RPG, where you\l"
	.string "play as an actor in a sitcom set\l"
	.string "in this nuclear wasteland desert.\l"
	.string "The writing is really off the wall.$"

SweltornInteriors_Text_Sweltornmin4:
	.string "Combun is a Pokémon from up north\n"
	.string "that some trainers bring along\l"
	.string "to Sweltorn Desert. That's because\l"
	.string "it evolves into a particular Pokémon\l"
	.string "when it battles here!\p"
	.string "I know there's other places that\n"
	.string "cause Combun to evolve, too,\l"
	.string "but I can't remember what they are.$"

SweltornInteriors_Text_Sweltornmin5:
	.string "Sometimes Jaramari like to\n"
	.string "play little pranks by disguising\l"
	.string "themselves as pots.\l"
	.string "I just think that's so annoying.$"

SweltornInteriors_Text_Sweltornmin6:
	.string "Thank heavens that Team Ozone\n"
	.string "stocks bottles of cold water\l"
	.string "in the checkpoint buildings...\l"
	.string "you get awfully parched out\l"
	.string "in the desert.$"
